name: Build Own Engine Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    name: Build Own Engine Game
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Solution
        run: msbuild "D:\RiderProjects\Socket\Socket.sln" /p:Configuration=Release /p:Platform=x64
